# Site settings
source:        .
destination:   _site
safe:          true
title:         I am a Maker
email:         sp03@kruk.eng.br
description:   "Personal Website and Blog from Luciano A. Kruk"
baseurl:       ""
url:           "http://www.kruk.eng.br"

#twitter_username: jekyllrb
github_username:   conconga
linkedin_username: lkruk

# Build settings
markdown:  kramdown
permalink: pretty
#highlighter: rouge

exclude:
    - sh_do2publish
